### ISSUE TITLE
About the output multiply 1/N

### ISSUE THREAD

**Issue by Kiyi-Lee** [t-hasegawa-FU/Easy-Ensemble#2]
That's a great work ! I have a question about the output multiplied by the 1/N operation. Does the 'x *= self.lambdas' implement this operation? Can I achieve the same result by using 'torch.mul(x, 1/N)' ? Meanwhile, if I use the conv2d operation to extract features, would it also be the same if I implement the output multiplied by 1/N before the fully connected (fc) layer and after the flatten operation?

**Comment by t-hasegawa-FU** [comment]
Thank you for your comment. That's correct, 'torch.mul(x, 1/N)' is the same as 'x *= self.lambdas'.
If you use the same lambdas for each path, such as 1 or 1/N, it's no problem if you multiply it after the fully connected layer (fc).
But, to set different lambdas to each ensemble path, you need to multiply the weights array (lambdas) before the fc because the results from each path have already been summarized after fc.
Actually, these two processes are not completely the same. Only the forward path is the same but the backward path is a little different.
However, it's not a big problem according to our preliminary experiments.
